### ISSUE TITLE
Feedback & Suggestions

### ISSUE THREAD

**Issue by mertbakir** [marcusolsson/grafana-hexmap-panel#2]
Hey, I tried the plugin and wanted to share my feedbacks.

I think you should

- remove the "All" text when there is no "Group by" defined.
- Use the hover tooltip and "Additional labels" options from Treemap plugin.

It just works, better than the old Polystat plugin. Good job.

You may also consider to display text inside the hexagons when the hexagons is big enough.

**Comment by marcusolsson** [comment]
Thank for using the plugin, and for your kind words 🙏 

I think all your suggestions are on point and within the scope of the plugin. The two first points are easy enough to fix right away. 

Before implementing text in hexagons however, I'd like to understand the use case a little better. What information would you like to display, and how would you like to configure it?

**Comment by mertbakir** [comment]
Actually, I don't have a real use case for text in hexagons. It will be useless eventually when there are so many hexagons. Yet, this feature was available in the [Polystat](https://grafana.com/grafana/plugins/grafana-polystat-panel?pg=plugins&plcmt=featured-undefined) plugin. I was using it in my previous job to display status of some services and the text was the service name. It can be useful when there are not so many hexagons to look at, So each hexagon can be considered as a "SingleStat" panel.

**Comment by marcusolsson** [comment]
I believe the Polystat panel focuses on time series, whereas this one uses the new _data frame_ format for generic data. 

I think one way to accomplish it would be to do add a Label dimension where you can choose the field to display in the hexagon.

**Comment by xkilian** [comment]
Label or metric value. As a metric value can also be converted to a emoji, it is very flexible and concise way to display data.

**Comment by marcusolsson** [comment]
I love the emoji idea :)

Could one of you submit a separate issue for displaying text in hexagons so that I can add it to the project board? We can keep this issue to track the first two suggestions maybe? I'm using a [project board](https://github.com/users/marcusolsson/projects/1) to manage issues across all my plugins, and prefer to keep it specific :)

**Comment by marcusolsson** [comment]
Fixed in 0.3.0
